FROM microsoft/azure-cli
MAINTAINER Amit Malik (amit@spektrasystems.com)

#install git

RUN apt-get update
RUN apt-get install -y git

# Install curl
RUN apt-get -y install curl

# Install openssl
RUN apt-get -y install openssl

#Install kubectl
RUN az aks install-cli
